server:
  port: 80

spring:
  application:
    name: cloud-comsumer-order

  cloud:
    consul:
      port: 8500
      host: 172.16.100.200
      discovery:
        service-name: ${spring.application.name}