server:
  port: 3344

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/QAQ5685150/springcloud-config
          search-paths:
            - springcloud-config
          default-label: main
  rabbitmq:
    host: 192.168.111.128
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    bus-env:
      enabled: true
      bus-refresh:
        enabled: true

