server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment
  cloud:
    consul:
      # consul注册中心地址
      host: 172.16.100.200
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
